#!/bin/sh
. "$(dirname $0)/_/husky.sh"

# 为GUI环境注入环境变量
PATH=$PATH:/usr/local/bin:/usr/local/sbin:/opt/homebrew/bin
# 执行代码检查，如果有问题会导致提交失败，或者自动修复。
# 如果有问题这里实际将commit拆成两步，第一步提交正常代码，第二步提交修复后的代码。
get_branch=`git symbolic-ref --short -q HEAD`
if [ "$get_branch" == "develop" ]; then
  npm run lint:all
fi

